- packages/core/src/options.ts
Instead of using attachments to upload the image's avatar, you can use Discord's own `embed/avatar`.
If someone deletes the images, they will soon not be able to be seen by embed.
> fix: use proper URLs for discord avatars

- packages/core/src/components.d.ts
- packages/core/src/components/discord-action-row/discord-action-row.css
- packages/core/src/components/discord-action-row/discord-action-row.tsx
- packages/core/src/components/discord-action-row/readme.md
- packages/core/src/components/discord-button/discord-button.css
- packages/core/src/components/discord-button/discord-button.tsx
- packages/core/src/components/discord-button/readme.md
- packages/core/src/components/discord-message/discord-message.tsx
- packages/core/src/components/svgs/launch-icon.tsx
- packages/core/src/index.html
- packages/react/src/index.ts
Adds component buttons (`discord-buttons`) and action rows (`discord-action-row`)
```html
<discord-message profile="skyra">
Here are some components!
<discord-attachments slot="components">
<discord-action-row>
<discord-button type="primary">Primary Button</discord-button>
<discord-button type="secondary">Secondary Button</discord-button>
<discord-button type="success">Green Button</discord-button>
<discord-button type="destructive">Red Button</discord-button>
<discord-button url="https://join.skyra.pw" emoji="/static/eyes.svg" emoji-name="👀">Link</discord-button>
</discord-action-row>
</discord-attachments>
</discord-message>
```
> feat: add component buttons

- packages/core/src/components/discord-command/discord-command.tsx
- packages/core/src/index.html
Small change, removes the `/` from `<discord-command>` since context menu commands don't have this
> fix(discord-command): remove prepending slash in names

- packages/core/src/components.d.ts
- packages/core/src/components/discord-tenor-video/discord-tenor-video.css
- packages/core/src/components/discord-tenor-video/discord-tenor-video.tsx
- packages/core/src/components/discord-tenor-video/readme.md
- packages/core/src/index.html
- packages/react/src/index.ts
I added a \<discord-tenor-video\> tag to play tenor gifs in video format (autoplayed looped no-control) (since discord API sends them as video embed and thats how their client renders it)
The styling is similar to discord-attachment and uses the attachment slot
Relevant to [this issue](https://github.com/skyra-project/discord-components/issues/126)
The changes in commit `57c26ad` are auto generated through `yarn build`
> feat: add `discord-tenor-video` component

- packages/core/src/components.d.ts
- packages/core/src/components/author-info/author-info.css
- packages/core/src/components/discord-message/discord-message.css
- packages/core/src/components/discord-message/discord-message.tsx
- packages/core/src/components/discord-system-message/discord-system-message.css
- packages/core/src/components/discord-system-message/discord-system-message.tsx
- packages/core/src/components/discord-thread-message/discord-thread-message.css
- packages/core/src/components/discord-thread-message/discord-thread-message.tsx
- packages/core/src/components/discord-thread-message/readme.md
- packages/core/src/components/discord-thread/discord-thread.css
- packages/core/src/components/discord-thread/discord-thread.tsx
- packages/core/src/components/discord-thread/readme.md
- packages/core/src/index.html
- packages/react/src/index.ts
Adds `<discord-thread>` and `<discord-thread-message>` to be used in `<discord-message>` and `<discord-system-message>`.
```html
<discord-messages>
<discord-system-message type="thread">
<i style="color: #a155ab">Favna</i> started a thread: <i>Skyra Suggestion Thread</i>. See all <i>threads</i>.
<discord-thread slot="thread" cta="2 Messages">
<discord-thread-message profile="skyra">Pong!</discord-thread-message>
</discord-thread>
</discord-system-message>
<discord-message profile="favna">
Let's make a thread!
<discord-thread slot="thread" name="A cool thread!">There are no messages in this thread yet.</discord-thread>
</discord-message>
</discord-messages>
```
> feat: Thread Accessories

- packages/core/src/components/discord-embed-description/discord-embed-description.css
- packages/core/src/index.html
Added styles for the html elements that are the basic markdown equivalents of:
inline emoji, inline code, multiline code, blockquote, and spoiler.
Upon closer inspection bold, italic, strikethrough, and underline are all used 'as is' already by discord so no additional styling needed. 
(Originally thought bold was off because it didn't match field titles, but it seems that's just the way discord does things).
Feel free to let me know if the classnames I included are ok or not - I don't have any reason I can't change them. 
I also did a little bit of cleverness around blockquotes to get the line to match discord's but without needing any additional tags, since a plain blockquote tag is all a markdown generator would create. And I did a little bit of extra on spoilers so that you can 'view' …
> feat(discord-embed-description): add styles for nested HTML tags

- packages/core/src/components.d.ts
- packages/core/src/components/discord-mention/discord-mention.css
- packages/core/src/components/discord-message/discord-message.css
- packages/core/src/components/discord-message/discord-message.tsx
- packages/core/src/components/discord-message/readme.md
- packages/core/src/components/svgs/ephemeral.tsx
- packages/core/src/index.html
Added ephemeral message option to `discord-message`.
Also pushed highlighting CSS rules `discord-message` rather than `discord-mention` and fixed the highlight border.
> feat: add ephemeral messages and highlight fixes

- packages/core/src/components.d.ts
- packages/core/src/components/discord-time/discord-time.css
- packages/core/src/components/discord-time/discord-time.tsx
- packages/core/src/components/discord-time/readme.md
- packages/core/src/index.html
- packages/react/src/index.ts
Adds discord timestamp styling (`discord-time`)
> feat: add `discord-time` component

- packages/core/src/components.d.ts
- packages/core/src/components/discord-mention/discord-mention.tsx
- packages/core/src/components/discord-mention/readme.md
- packages/core/src/index.html
Display slash commands as mentionable in the component. This resolves #287.
> feat: mention for slash commands

- packages/core/demo/index.html
- packages/core/package.json
- packages/core/src/components/_private/DiscordMediaAttachmentStyles.ts
- packages/core/src/components/_private/DiscordMediaLifecycle.ts
- packages/core/src/components/_private/DiscordPlaybackControlStyles.ts
- packages/core/src/components/_private/DiscordVolumeControlStyles.ts
- packages/core/src/components/discord-audio-attachment/DiscordAudioAttachment.ts
- packages/core/src/components/discord-video-attachment/DiscordVideoAttachment.ts
- packages/core/src/components/svgs/AudioVideoVolumeAbove50PercentIcon.ts
- packages/core/src/components/svgs/VideoFullScreenIcon.ts
- packages/core/src/components/svgs/VideoPausePopIcon.ts
- packages/core/src/components/svgs/VideoPlayPausePopIcon.ts
- packages/core/src/components/svgs/VideoPlayPopIcon.ts
- packages/core/src/index.ts
- packages/react/src/index.ts
> feat: add video attachment component

- packages/core/src/components/discord-embed/DiscordEmbed.ts
Adding the possibility of skipping lines if you use a textarea to insert text and problems of not giving more than one space
> fix: added the possibility of skipping lines for discord-embed titles

- packages/core/src/components/discord-embed-field/DiscordEmbedField.ts
Here is the same feature that I did and Favna perfected it in "discord-embed" but in the name of the field (I really use this)
> fix: added the possibility of skipping lines for discord-embed-field titles

- packages/core/src/components/discord-embed/DiscordEmbed.ts
I don't know if there is any problem in having the tag "div" but without it when the person uses it skips only one line it does not skip and when it skips two it skips one then it goes back to normal
> fix: add skiping one line

- packages/core/src/components/discord-reply/DiscordReply.ts
Rouge `}` shown when using the following code:
```jsx
<DiscordReply
slot="reply"
profile="you"
author="You"
avatar="./Logo.svg"
roleColor="#1e88e5"
bot={true}
verified={true}
command={true}
>
<p>Click to see command</p>
</DiscordReply>
```
> fix(discord-reply): Removed rouge closing curly brace

- packages/core/src/components/discord-action-row/DiscordActionRow.ts
The "flex-wrap" was wrong causing the buttons to always stay on the same line and making them lose responsiveness, taking into account that the discord itself is the way I left it, I recommend leaving it like this
> fix(discord-action-row): wrap using "flex-wrap"

- packages/core/src/components/discord-invite/DiscordInvite.ts
I changed some styles because it made the invitation a single size and breaking the responsiveness and updated the information of the invitation because they were not changing the direction and added some "text-overflow"
With my modification
The original
> fix(discord-invite): improve styling

- packages/core/src/components/discord-input-text/DiscordInputText.ts
The new modal component had a slight issue with the bordercolor always being there instead of only on the light mode version. This pull request edits that to make it more inline with discords official style.
Before:
After:
> fix: remove border on modal input

- packages/core/src/components/discord-time/DiscordTime.ts
Discord doesnt have wrapping on timestamps, so this ensures no wrapping.
> fix: prevent timestamp wrapping

- packages/core/src/components/discord-command/DiscordCommand.ts
I only realized now that the context user name is the wrong color in light mode
> fix: correcting context-user-name-color

- packages/core/src/components/discord-embed-field/DiscordEmbedField.ts
- packages/core/src/components/discord-embed-fields/DiscordEmbedFields.ts
Fixes #509
Fix the issue with the bottom field not spanning across three inline fields in the embed.
> fix: inline field bug in Discord embed

- packages/core/demo/index.html
- packages/core/src/components/discord-messages/DiscordMessages.ts
Allows the `discord-messages` element to accept `channel` and `type` props which adds a header above the messages.
Example:
> feat: added option to add the channel name above discord messages
